import { PrismaClient, Size } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import "dotenv/config";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("🌱 Seeding products...");

  // Clear existing product data
  await prisma.orderItem.deleteMany();
  await prisma.cartItem.deleteMany();
  await prisma.wishlistItem.deleteMany();
  await prisma.productSize.deleteMany();
  await prisma.product.deleteMany();
  console.log("🗑️  Cleared existing products");

  // Fetch categories
  const categoryList = await prisma.category.findMany();
  const categories: Record<string, string> = {};
  for (const cat of categoryList) {
    categories[cat.slug] = cat.id;
  }

  if (Object.keys(categories).length === 0) {
    throw new Error("No categories found. Run the main seed (prisma db seed) first.");
  }

  const products = [
    // ── KURTAS (5) ──────────────────────────────────────────────────────────
    {
      name: "Pink Floral Anarkali Kurta",
      slug: "pink-floral-anarkali-kurta",
      shortDescription: "Elegant floral Anarkali kurta with fine embroidery — perfect for festive occasions.",
      description: "<p>Elegant floral printed Anarkali kurta with fine embroidery. Perfect for festive occasions.</p><ul><li>Fabric: Cotton Blend</li><li>Fit: Regular</li><li>Care: Machine wash cold</li></ul>",
      price: 1299,
      comparePrice: 1999,
      categoryId: categories["kurtas"],
      isActive: true,
      isFeatured: true,
      isTrending: true,
      isOffer: false,
      images: [
        "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1614093302611-8efc4a99faea?w=600&h=800&fit=crop",
      ],
      tags: ["anarkali", "festive", "floral"],
      sizes: [
        { size: Size.XS, stock: 5 },
        { size: Size.S, stock: 8 },
        { size: Size.M, stock: 10 },
        { size: Size.L, stock: 7 },
        { size: Size.XL, stock: 4 },
      ],
    },
    {
      name: "Blue Embroidered Straight Kurta",
      slug: "blue-embroidered-straight-kurta",
      shortDescription: "Classic straight-cut kurta with delicate neckline embroidery — versatile for work and casual wear.",
      description: "<p>Classic straight-cut kurta with delicate embroidery on neckline. Versatile for work and casual wear.</p><ul><li>Fabric: Cotton</li><li>Fit: Straight</li><li>Care: Hand wash recommended</li></ul>",
      price: 899,
      comparePrice: 1499,
      categoryId: categories["kurtas"],
      isActive: true,
      isFeatured: false,
      isTrending: true,
      isOffer: true,
      images: [
        "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&h=800&fit=crop",
      ],
      tags: ["kurta", "casual", "embroidery"],
      sizes: [
        { size: Size.S, stock: 6 },
        { size: Size.M, stock: 12 },
        { size: Size.L, stock: 9 },
        { size: Size.XL, stock: 5 },
        { size: Size.XXL, stock: 3 },
      ],
    },
    {
      name: "Mustard Yellow A-Line Kurta",
      slug: "mustard-yellow-aline-kurta",
      shortDescription: "Vibrant mustard A-line kurta with block print hem — great for casual and festive wear.",
      description: "<p>Vibrant mustard A-line kurta featuring block print detailing at the hem. Great for casual outings and festive gatherings.</p><ul><li>Fabric: Rayon</li><li>Fit: A-line</li><li>Care: Machine wash cold</li></ul>",
      price: 799,
      comparePrice: 1299,
      categoryId: categories["kurtas"],
      isActive: true,
      isFeatured: true,
      isTrending: false,
      isOffer: true,
      images: [
        "https://images.unsplash.com/photo-1614093302611-8efc4a99faea?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&h=800&fit=crop",
      ],
      tags: ["kurta", "block-print", "casual"],
      sizes: [
        { size: Size.XS, stock: 4 },
        { size: Size.S, stock: 9 },
        { size: Size.M, stock: 11 },
        { size: Size.L, stock: 6 },
        { size: Size.XL, stock: 3 },
      ],
    },
    {
      name: "White Chikankari Kurti",
      slug: "white-chikankari-kurti",
      shortDescription: "Timeless white chikankari kurti — a wardrobe staple in luxurious cotton fabric.",
      description: "<p>Timeless white kurti with authentic chikankari embroidery. A wardrobe staple crafted in luxurious cotton fabric.</p><ul><li>Fabric: Pure Cotton</li><li>Embroidery: Chikankari</li><li>Fit: Regular</li><li>Care: Hand wash in cold water</li></ul>",
      price: 1099,
      comparePrice: 1799,
      categoryId: categories["kurtas"],
      isActive: true,
      isFeatured: true,
      isTrending: true,
      isOffer: false,
      images: [
        "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=600&h=800&fit=crop",
      ],
      tags: ["chikankari", "kurta", "white", "classic"],
      sizes: [
        { size: Size.XS, stock: 3 },
        { size: Size.S, stock: 7 },
        { size: Size.M, stock: 10 },
        { size: Size.L, stock: 8 },
        { size: Size.XL, stock: 5 },
        { size: Size.XXL, stock: 2 },
      ],
    },
    {
      name: "Green Bandhani Kurta",
      slug: "green-bandhani-kurta",
      shortDescription: "Gorgeous green bandhani-print kurta — vibrant Rajasthani craftsmanship for festive days.",
      description: "<p>Gorgeous green kurta featuring traditional bandhani print. Vibrant Rajasthani craftsmanship perfect for festive days.</p><ul><li>Fabric: Georgette</li><li>Print: Bandhani</li><li>Fit: Regular</li><li>Care: Dry clean recommended</li></ul>",
      price: 1199,
      comparePrice: 1899,
      categoryId: categories["kurtas"],
      isActive: true,
      isFeatured: false,
      isTrending: true,
      isOffer: false,
      images: [
        "https://images.unsplash.com/photo-1614093302611-8efc4a99faea?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&h=800&fit=crop",
      ],
      tags: ["bandhani", "rajasthani", "festive"],
      sizes: [
        { size: Size.S, stock: 5 },
        { size: Size.M, stock: 8 },
        { size: Size.L, stock: 6 },
        { size: Size.XL, stock: 4 },
        { size: Size.XXL, stock: 2 },
      ],
    },

    // ── DRESSES (5) ─────────────────────────────────────────────────────────
    {
      name: "Maxi Floral Dress",
      slug: "maxi-floral-dress",
      shortDescription: "Flowing maxi dress with vibrant floral print — ideal for summer outings and beach trips.",
      description: "<p>Flowing maxi dress with vibrant floral print. Ideal for summer outings.</p><ul><li>Fabric: Chiffon</li><li>Length: Full length</li><li>Care: Gentle machine wash</li></ul>",
      price: 1599,
      comparePrice: 2299,
      categoryId: categories["dresses"],
      isActive: true,
      isFeatured: true,
      isTrending: false,
      isOffer: false,
      images: [
        "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600&h=800&fit=crop",
      ],
      tags: ["maxi", "summer", "floral"],
      sizes: [
        { size: Size.XS, stock: 4 },
        { size: Size.S, stock: 7 },
        { size: Size.M, stock: 8 },
        { size: Size.L, stock: 6 },
      ],
    },
    {
      name: "Off-Shoulder Midi Dress",
      slug: "off-shoulder-midi-dress",
      shortDescription: "Elegant off-shoulder midi dress with flared skirt — great for parties and date nights.",
      description: "<p>Elegant off-shoulder midi dress with flared skirt. Great for parties and date nights.</p><ul><li>Fabric: Crepe</li><li>Length: Midi</li><li>Style: Off-shoulder</li><li>Care: Hand wash or dry clean</li></ul>",
      price: 1399,
      comparePrice: 1999,
      categoryId: categories["dresses"],
      isActive: true,
      isFeatured: true,
      isTrending: true,
      isOffer: true,
      images: [
        "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&h=800&fit=crop",
      ],
      tags: ["midi", "party", "off-shoulder"],
      sizes: [
        { size: Size.XS, stock: 5 },
        { size: Size.S, stock: 8 },
        { size: Size.M, stock: 10 },
        { size: Size.L, stock: 6 },
      ],
    },
    {
      name: "Wrap Sundress - Tropical Print",
      slug: "wrap-sundress-tropical-print",
      shortDescription: "Breezy wrap sundress in tropical print — effortlessly chic for vacations and brunch.",
      description: "<p>Breezy wrap sundress in a vibrant tropical print. Effortlessly chic for vacations, brunches and casual days out.</p><ul><li>Fabric: Viscose</li><li>Style: Wrap</li><li>Care: Machine wash cold</li></ul>",
      price: 1099,
      comparePrice: 1699,
      categoryId: categories["dresses"],
      isActive: true,
      isFeatured: false,
      isTrending: true,
      isOffer: true,
      images: [
        "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600&h=800&fit=crop",
      ],
      tags: ["wrap", "summer", "casual"],
      sizes: [
        { size: Size.XS, stock: 6 },
        { size: Size.S, stock: 9 },
        { size: Size.M, stock: 10 },
        { size: Size.L, stock: 7 },
        { size: Size.XL, stock: 3 },
      ],
    },
    {
      name: "Black Bodycon Dress",
      slug: "black-bodycon-dress",
      shortDescription: "Sleek black bodycon dress with ruched sides — a timeless choice for evening events.",
      description: "<p>Sleek black bodycon dress with ruched sides for a flattering fit. A timeless choice for evening events and cocktail parties.</p><ul><li>Fabric: Stretch Jersey</li><li>Length: Mini</li><li>Style: Bodycon</li><li>Care: Machine wash cold, lay flat to dry</li></ul>",
      price: 1249,
      comparePrice: 1899,
      categoryId: categories["dresses"],
      isActive: true,
      isFeatured: true,
      isTrending: true,
      isOffer: false,
      images: [
        "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&h=800&fit=crop",
      ],
      tags: ["bodycon", "evening", "black"],
      sizes: [
        { size: Size.XS, stock: 5 },
        { size: Size.S, stock: 8 },
        { size: Size.M, stock: 9 },
        { size: Size.L, stock: 5 },
        { size: Size.XL, stock: 2 },
      ],
    },
    {
      name: "Pastel Shirt Dress",
      slug: "pastel-shirt-dress",
      shortDescription: "Relaxed pastel shirt dress with belt — smart-casual style for work-from-home and outings.",
      description: "<p>Relaxed pastel shirt dress with detachable belt. Smart-casual style perfect for work-from-home days and weekend outings.</p><ul><li>Fabric: Cotton Poplin</li><li>Length: Midi</li><li>Style: Shirt dress with belt</li><li>Care: Machine washable</li></ul>",
      price: 1349,
      comparePrice: 1999,
      categoryId: categories["dresses"],
      isActive: true,
      isFeatured: false,
      isTrending: false,
      isOffer: false,
      images: [
        "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&h=800&fit=crop",
      ],
      tags: ["shirt-dress", "casual", "pastel"],
      sizes: [
        { size: Size.XS, stock: 4 },
        { size: Size.S, stock: 7 },
        { size: Size.M, stock: 10 },
        { size: Size.L, stock: 8 },
        { size: Size.XL, stock: 4 },
        { size: Size.XXL, stock: 2 },
      ],
    },

    // ── TOPS (4) ─────────────────────────────────────────────────────────────
    {
      name: "Crop Top - Tie Dye",
      slug: "crop-top-tie-dye",
      shortDescription: "Trending tie-dye crop top for casual wear — pairs perfectly with high-waist jeans.",
      description: "<p>Trending tie-dye crop top for casual wear. Perfect with high-waist jeans.</p><ul><li>Fabric: Cotton</li><li>Style: Cropped</li><li>Care: Machine wash cold, tumble dry low</li></ul>",
      price: 499,
      comparePrice: 799,
      categoryId: categories["tops"],
      isActive: true,
      isFeatured: false,
      isTrending: true,
      isOffer: true,
      images: [
        "https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=600&h=800&fit=crop",
      ],
      tags: ["crop", "casual", "tie-dye"],
      sizes: [
        { size: Size.XS, stock: 10 },
        { size: Size.S, stock: 12 },
        { size: Size.M, stock: 8 },
        { size: Size.L, stock: 5 },
      ],
    },
    {
      name: "Striped Linen Shirt",
      slug: "striped-linen-shirt",
      shortDescription: "Classic striped linen shirt — airy and stylish for all-day comfort.",
      description: "<p>Classic striped linen shirt, airy and stylish for all-day comfort. Goes with trousers, jeans or palazzo pants.</p><ul><li>Fabric: Linen</li><li>Style: Regular shirt</li><li>Care: Machine wash gentle cycle</li></ul>",
      price: 699,
      comparePrice: 1099,
      categoryId: categories["tops"],
      isActive: true,
      isFeatured: false,
      isTrending: false,
      isOffer: true,
      images: [
        "https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=600&h=800&fit=crop",
      ],
      tags: ["linen", "casual", "stripes"],
      sizes: [
        { size: Size.S, stock: 8 },
        { size: Size.M, stock: 12 },
        { size: Size.L, stock: 10 },
        { size: Size.XL, stock: 6 },
        { size: Size.XXL, stock: 3 },
      ],
    },
    {
      name: "Embroidered Boho Top",
      slug: "embroidered-boho-top",
      shortDescription: "Flowy boho top with thread embroidery on yoke — great for casual and festival looks.",
      description: "<p>Flowy boho top with intricate thread embroidery on the yoke. Great for casual outings and festival looks.</p><ul><li>Fabric: Rayon</li><li>Style: Boho / Peasant</li><li>Care: Hand wash cold</li></ul>",
      price: 799,
      comparePrice: 1299,
      categoryId: categories["tops"],
      isActive: true,
      isFeatured: true,
      isTrending: true,
      isOffer: false,
      images: [
        "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=600&h=800&fit=crop",
      ],
      tags: ["boho", "embroidery", "festival"],
      sizes: [
        { size: Size.XS, stock: 5 },
        { size: Size.S, stock: 9 },
        { size: Size.M, stock: 11 },
        { size: Size.L, stock: 7 },
        { size: Size.XL, stock: 4 },
      ],
    },
    {
      name: "Solid Peplum Top",
      slug: "solid-peplum-top",
      shortDescription: "Chic solid peplum top — flattering cut that pairs well with pencil skirts or trousers.",
      description: "<p>Chic solid peplum top with a flattering flared hem. Pairs beautifully with pencil skirts, trousers or straight-fit jeans.</p><ul><li>Fabric: Polyester Blend</li><li>Style: Peplum</li><li>Care: Dry clean or hand wash</li></ul>",
      price: 649,
      comparePrice: 999,
      categoryId: categories["tops"],
      isActive: true,
      isFeatured: false,
      isTrending: false,
      isOffer: true,
      images: [
        "https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=600&h=800&fit=crop",
      ],
      tags: ["peplum", "office", "casual"],
      sizes: [
        { size: Size.XS, stock: 6 },
        { size: Size.S, stock: 10 },
        { size: Size.M, stock: 12 },
        { size: Size.L, stock: 8 },
        { size: Size.XL, stock: 4 },
        { size: Size.XXL, stock: 2 },
      ],
    },

    // ── LEHENGAS (4) ─────────────────────────────────────────────────────────
    {
      name: "Red Lehenga Choli",
      slug: "red-lehenga-choli",
      shortDescription: "Stunning red bridal lehenga with intricate zari work — comes with matching dupatta.",
      description: "<p>Stunning red bridal lehenga with intricate zari work. Comes with matching dupatta.</p><ul><li>Fabric: Silk Blend</li><li>Includes: Lehenga, Choli &amp; Dupatta</li><li>Occasion: Bridal / Wedding</li><li>Care: Dry clean only</li></ul>",
      price: 4999,
      comparePrice: 7999,
      categoryId: categories["lehengas"],
      isActive: true,
      isFeatured: true,
      isTrending: true,
      isOffer: false,
      images: [
        "https://images.unsplash.com/photo-1583391733956-3c5f7a4b2ce0?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&h=800&fit=crop",
      ],
      tags: ["bridal", "occasion", "zari"],
      sizes: [
        { size: Size.S, stock: 3 },
        { size: Size.M, stock: 5 },
        { size: Size.L, stock: 4 },
        { size: Size.XL, stock: 2 },
      ],
    },
    {
      name: "Pink Sequin Lehenga",
      slug: "pink-sequin-lehenga",
      shortDescription: "Dazzling pink lehenga with heavy sequin work — for receptions, sangeets and grand celebrations.",
      description: "<p>Dazzling pink lehenga adorned with heavy sequin work. Perfect for receptions, sangeets and grand celebrations.</p><ul><li>Fabric: Net with lining</li><li>Includes: Lehenga, Choli &amp; Dupatta</li><li>Embellishment: Sequins &amp; beadwork</li><li>Care: Dry clean only</li></ul>",
      price: 5999,
      comparePrice: 9999,
      categoryId: categories["lehengas"],
      isActive: true,
      isFeatured: true,
      isTrending: true,
      isOffer: false,
      images: [
        "https://images.unsplash.com/photo-1583391733956-3c5f7a4b2ce0?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1614093302611-8efc4a99faea?w=600&h=800&fit=crop",
      ],
      tags: ["sequin", "party", "bridal", "pink"],
      sizes: [
        { size: Size.S, stock: 2 },
        { size: Size.M, stock: 4 },
        { size: Size.L, stock: 3 },
        { size: Size.XL, stock: 2 },
      ],
    },
    {
      name: "Navy Blue Embroidered Lehenga",
      slug: "navy-blue-embroidered-lehenga",
      shortDescription: "Royal navy blue lehenga with resham embroidery — elegant for weddings and festive functions.",
      description: "<p>Royal navy blue lehenga with intricate resham embroidery. Elegant choice for weddings and festive functions.</p><ul><li>Fabric: Raw Silk</li><li>Includes: Lehenga, Choli &amp; Dupatta</li><li>Embroidery: Resham threadwork</li><li>Care: Dry clean only</li></ul>",
      price: 3999,
      comparePrice: 6499,
      categoryId: categories["lehengas"],
      isActive: true,
      isFeatured: false,
      isTrending: true,
      isOffer: true,
      images: [
        "https://images.unsplash.com/photo-1583391733956-3c5f7a4b2ce0?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&h=800&fit=crop",
      ],
      tags: ["lehenga", "navy", "embroidered", "wedding"],
      sizes: [
        { size: Size.S, stock: 3 },
        { size: Size.M, stock: 5 },
        { size: Size.L, stock: 4 },
        { size: Size.XL, stock: 2 },
        { size: Size.XXL, stock: 1 },
      ],
    },
    {
      name: "Mint Green Indo-Western Lehenga",
      slug: "mint-green-indo-western-lehenga",
      shortDescription: "Contemporary indo-western lehenga in mint green — ideal for mehendi and haldi ceremonies.",
      description: "<p>Contemporary indo-western lehenga in refreshing mint green. Ideal for mehendi and haldi ceremonies.</p><ul><li>Fabric: Chanderi</li><li>Includes: Crop Top &amp; Lehenga Skirt</li><li>Style: Indo-Western</li><li>Care: Hand wash or dry clean</li></ul>",
      price: 2999,
      comparePrice: 4999,
      categoryId: categories["lehengas"],
      isActive: true,
      isFeatured: true,
      isTrending: false,
      isOffer: false,
      images: [
        "https://images.unsplash.com/photo-1614093302611-8efc4a99faea?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1583391733956-3c5f7a4b2ce0?w=600&h=800&fit=crop",
      ],
      tags: ["indo-western", "mehendi", "mint"],
      sizes: [
        { size: Size.S, stock: 4 },
        { size: Size.M, stock: 6 },
        { size: Size.L, stock: 5 },
        { size: Size.XL, stock: 3 },
      ],
    },

    // ── SAREES (4) ───────────────────────────────────────────────────────────
    {
      name: "Printed Saree with Blouse",
      slug: "printed-saree-with-blouse",
      shortDescription: "Graceful printed saree with ready-to-wear blouse — a timeless choice for every occasion.",
      description: "<p>Graceful printed saree with ready-to-wear blouse. A timeless choice for every occasion.</p><ul><li>Fabric: Georgette</li><li>Length: 5.5 metres</li><li>Includes: Saree &amp; Blouse piece</li><li>Care: Dry clean recommended</li></ul>",
      price: 2199,
      comparePrice: 3499,
      categoryId: categories["sarees"],
      isActive: true,
      isFeatured: true,
      isTrending: false,
      isOffer: true,
      images: [
        "https://images.unsplash.com/photo-1583391733956-3c5f7a4b2ce0?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1614093302611-8efc4a99faea?w=600&h=800&fit=crop",
      ],
      tags: ["saree", "traditional", "printed"],
      sizes: [
        { size: Size.S, stock: 8 },
        { size: Size.M, stock: 10 },
        { size: Size.L, stock: 7 },
        { size: Size.XL, stock: 4 },
      ],
    },
    {
      name: "Banarasi Silk Saree",
      slug: "banarasi-silk-saree",
      shortDescription: "Luxurious Banarasi silk saree with gold zari border — perfect for weddings and festivals.",
      description: "<p>Luxurious Banarasi silk saree with a rich gold zari border and woven motifs. Perfect for weddings, festivals and special occasions.</p><ul><li>Fabric: Banarasi Silk</li><li>Length: 6 metres with blouse piece</li><li>Border: Gold zari</li><li>Care: Dry clean only</li></ul>",
      price: 4499,
      comparePrice: 7499,
      categoryId: categories["sarees"],
      isActive: true,
      isFeatured: true,
      isTrending: true,
      isOffer: false,
      images: [
        "https://images.unsplash.com/photo-1583391733956-3c5f7a4b2ce0?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&h=800&fit=crop",
      ],
      tags: ["banarasi", "silk", "wedding", "zari"],
      sizes: [
        { size: Size.S, stock: 5 },
        { size: Size.M, stock: 7 },
        { size: Size.L, stock: 6 },
        { size: Size.XL, stock: 3 },
      ],
    },
    {
      name: "Cotton Handloom Saree",
      slug: "cotton-handloom-saree",
      shortDescription: "Comfortable handloom cotton saree in earthy tones — perfect for everyday and office wear.",
      description: "<p>Comfortable handloom cotton saree in beautiful earthy tones. Perfect for everyday wear and office occasions.</p><ul><li>Fabric: Handloom Cotton</li><li>Length: 5.5 metres with blouse piece</li><li>Care: Machine wash gentle cycle</li></ul>",
      price: 1499,
      comparePrice: 2499,
      categoryId: categories["sarees"],
      isActive: true,
      isFeatured: false,
      isTrending: false,
      isOffer: true,
      images: [
        "https://images.unsplash.com/photo-1614093302611-8efc4a99faea?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1583391733956-3c5f7a4b2ce0?w=600&h=800&fit=crop",
      ],
      tags: ["handloom", "cotton", "casual", "office"],
      sizes: [
        { size: Size.S, stock: 10 },
        { size: Size.M, stock: 14 },
        { size: Size.L, stock: 10 },
        { size: Size.XL, stock: 6 },
        { size: Size.XXL, stock: 3 },
      ],
    },
    {
      name: "Chiffon Designer Saree",
      slug: "chiffon-designer-saree",
      shortDescription: "Elegant chiffon saree with embellished border — a graceful choice for parties and receptions.",
      description: "<p>Elegant chiffon saree with an embellished border and pallu. A graceful choice for parties, receptions and festive occasions.</p><ul><li>Fabric: Chiffon</li><li>Length: 5.5 metres</li><li>Embellishment: Stone-work border</li><li>Care: Dry clean recommended</li></ul>",
      price: 2799,
      comparePrice: 4299,
      categoryId: categories["sarees"],
      isActive: true,
      isFeatured: true,
      isTrending: true,
      isOffer: false,
      images: [
        "https://images.unsplash.com/photo-1583391733956-3c5f7a4b2ce0?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1614093302611-8efc4a99faea?w=600&h=800&fit=crop",
      ],
      tags: ["chiffon", "party", "embellished"],
      sizes: [
        { size: Size.S, stock: 6 },
        { size: Size.M, stock: 9 },
        { size: Size.L, stock: 7 },
        { size: Size.XL, stock: 4 },
      ],
    },

    // ── ETHNIC SETS (3) ──────────────────────────────────────────────────────
    {
      name: "Ethnic Palazzo Set",
      slug: "ethnic-palazzo-set",
      shortDescription: "Comfortable ethnic palazzo suit with dupatta — perfect for casual and semi-formal occasions.",
      description: "<p>Comfortable ethnic palazzo suit with dupatta. Perfect for casual and semi-formal occasions.</p><ul><li>Fabric: Rayon</li><li>Includes: Kurta, Palazzo &amp; Dupatta</li><li>Fit: Relaxed</li><li>Care: Machine wash cold</li></ul>",
      price: 1099,
      comparePrice: 1699,
      categoryId: categories["ethnic-sets"],
      isActive: true,
      isFeatured: false,
      isTrending: true,
      isOffer: false,
      images: [
        "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&h=800&fit=crop",
      ],
      tags: ["palazzo", "ethnic", "comfortable"],
      sizes: [
        { size: Size.S, stock: 6 },
        { size: Size.M, stock: 9 },
        { size: Size.L, stock: 7 },
        { size: Size.XL, stock: 3 },
        { size: Size.XXL, stock: 2 },
      ],
    },
    {
      name: "Patiala Salwar Suit",
      slug: "patiala-salwar-suit",
      shortDescription: "Vibrant Punjabi-style Patiala salwar suit with phulkari dupatta — festive and fun.",
      description: "<p>Vibrant Punjabi-style Patiala salwar suit paired with a beautiful phulkari dupatta. Festive, fun and full of colour.</p><ul><li>Fabric: Cotton Blend</li><li>Includes: Kurti, Patiala Salwar &amp; Dupatta</li><li>Style: Patiala</li><li>Care: Machine wash cold</li></ul>",
      price: 1399,
      comparePrice: 2199,
      categoryId: categories["ethnic-sets"],
      isActive: true,
      isFeatured: true,
      isTrending: true,
      isOffer: false,
      images: [
        "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=600&h=800&fit=crop",
      ],
      tags: ["patiala", "punjabi", "phulkari", "festive"],
      sizes: [
        { size: Size.S, stock: 5 },
        { size: Size.M, stock: 8 },
        { size: Size.L, stock: 7 },
        { size: Size.XL, stock: 4 },
        { size: Size.XXL, stock: 2 },
      ],
    },
    {
      name: "Sharara Suit - Festive Edition",
      slug: "sharara-suit-festive-edition",
      shortDescription: "Gorgeous sharara suit with mirror work — a head-turning choice for festivals and functions.",
      description: "<p>Gorgeous sharara suit featuring intricate mirror work. A head-turning choice for festivals, functions and family gatherings.</p><ul><li>Fabric: Georgette</li><li>Includes: Kurti, Sharara &amp; Dupatta</li><li>Embellishment: Mirror work</li><li>Care: Dry clean recommended</li></ul>",
      price: 2499,
      comparePrice: 3999,
      categoryId: categories["ethnic-sets"],
      isActive: true,
      isFeatured: true,
      isTrending: true,
      isOffer: true,
      images: [
        "https://images.unsplash.com/photo-1614093302611-8efc4a99faea?w=600&h=800&fit=crop",
        "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=600&h=800&fit=crop",
      ],
      tags: ["sharara", "mirror-work", "festive", "party"],
      sizes: [
        { size: Size.S, stock: 4 },
        { size: Size.M, stock: 7 },
        { size: Size.L, stock: 6 },
        { size: Size.XL, stock: 3 },
      ],
    },
  ];

  for (const p of products) {
    const { sizes, ...productData } = p;
    const created = await prisma.product.create({ data: productData });
    await prisma.productSize.createMany({
      data: sizes.map((s) => ({ ...s, productId: created.id })),
    });
  }

  console.log(`✅ Products seeded: ${products.length}`);
  console.log("\n🎉 Product seeding complete!");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
